server: # REST and WS server
  port: 3156
  address: 0.0.0.0
lavalink:
  server:
    password: "Lumine_Lumine"
    sources:
      youtube: true
      bandcamp: false
      soundcloud: true
      twitch: false
      vimeo: false
      mixer: false
      http: true
      local: true
    bufferDurationMs: 150
    youtubePlaylistLoadLimit: 5   # 5 Means ... 500 Songs maximum / Playlist
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
      
metrics:
  prometheus:
    enabled: false
    endpoint: /metrics
sentry:
  dsn: ""
logging:
  file:
    max-history: 5
    max-size: 100MB
  path: ./logs/
  level:
    root: INFO
    lavalink: INFO